-- ============================================================
-- Seed data — ports current hardcoded content from data/*.ts
-- so the public site keeps working once it reads from Supabase.
-- ============================================================

insert into products (slug, name, category, price, description, long_description, features, gallery, image, sort_order) values
('website-company-profile', 'Website Company Profile', 'Web Development', 'Rp 3.500.000',
 'Website profil perusahaan yang modern, responsif, dan siap tampil profesional.',
 'Paket Website Company Profile dirancang untuk membantu bisnis kamu tampil lebih kredibel di mata calon klien. Dibangun dengan desain modern, struktur konten yang jelas, dan tampilan yang responsif di semua perangkat, mulai dari desktop hingga smartphone. Cocok untuk perusahaan, instansi, maupun UMKM yang ingin memperkenalkan profil, layanan, dan portofolio mereka secara profesional di internet.',
 ARRAY['Desain custom sesuai identitas brand', 'Hingga 5 halaman (Home, Tentang, Layanan, Portofolio, Kontak)', 'Tampilan responsif di desktop & mobile', 'Optimasi SEO dasar', 'Formulir kontak terintegrasi email', 'Gratis 1 tahun domain & hosting', 'Garansi revisi 2x'],
 ARRAY['/images/portofolio7.jpg', '/images/portofolio8.jpg', '/images/portofolio2.jpg'],
 '/images/portofolio7.jpg', 0),
('website-e-commerce', 'Website E-Commerce', 'Web Development', 'Rp 7.500.000',
 'Toko online lengkap dengan katalog produk, keranjang, dan integrasi pembayaran.',
 'Wujudkan toko online kamu sendiri dengan paket Website E-Commerce. Dilengkapi dengan sistem katalog produk, keranjang belanja, checkout, hingga integrasi payment gateway agar transaksi pelanggan berjalan lancar dan aman. Panel admin yang mudah digunakan membuat kamu bisa mengelola produk, pesanan, dan stok tanpa perlu keahlian teknis.',
 ARRAY['Katalog produk & kategori tanpa batas', 'Keranjang belanja & checkout otomatis', 'Integrasi payment gateway (transfer, e-wallet, QRIS)', 'Panel admin untuk kelola produk & pesanan', 'Manajemen stok otomatis', 'Tampilan responsif di semua perangkat', 'Garansi revisi 2x'],
 ARRAY['/images/portofolio1.jpg', '/images/portofolio4.jpg', '/images/portofolio6.jpg'],
 '/images/portofolio1.jpg', 1),
('paket-branding-logo', 'Paket Branding & Logo', 'Graphic Design', 'Rp 1.500.000',
 'Identitas visual brand mulai dari logo, palet warna, hingga brand guideline.',
 'Bangun identitas visual yang kuat dan konsisten untuk bisnis kamu. Paket ini mencakup perancangan logo, pemilihan palet warna, tipografi, hingga panduan penggunaan brand (brand guideline) agar tampilan brand kamu tetap konsisten di semua media, baik cetak maupun digital.',
 ARRAY['3 pilihan konsep logo', 'Revisi hingga desain final disetujui', 'File logo format vector (AI, EPS, SVG) & raster (PNG, JPG)', 'Panduan warna & tipografi brand', 'Brand guideline (PDF)', 'Mockup penerapan logo pada media'],
 ARRAY['/images/portofolio8.jpg', '/images/graphic-design.png'],
 '/images/portofolio8.jpg', 2),
('undangan-pernikahan-digital', 'Undangan Pernikahan Digital', 'Graphic Design', 'Rp 500.000',
 'Undangan digital interaktif dengan desain elegan dan mudah dibagikan.',
 'Sebarkan undangan pernikahan kamu secara praktis dan elegan melalui format digital. Dilengkapi dengan galeri foto, informasi acara, peta lokasi, hingga fitur ucapan online, sehingga tamu undangan bisa mengakses semua informasi acara hanya melalui satu tautan yang bisa dibagikan lewat WhatsApp maupun media sosial.',
 ARRAY['Desain elegan & dapat disesuaikan tema', 'Galeri foto pasangan', 'Informasi acara & hitung mundur (countdown)', 'Peta lokasi acara terintegrasi', 'Fitur ucapan & doa online', 'Tautan mudah dibagikan ke WhatsApp/media sosial'],
 ARRAY['/images/portofolio5.jpg', '/images/celebration.png'],
 '/images/portofolio5.jpg', 3),
('paket-konten-media-sosial', 'Paket Konten Media Sosial', 'Digital Marketing', 'Rp 2.000.000',
 'Konten feed dan story bulanan untuk menjaga konsistensi brand di media sosial.',
 'Jaga konsistensi kehadiran brand kamu di media sosial dengan paket konten bulanan. Tim kreatif kami akan merancang konten feed dan story yang menarik dan sesuai dengan identitas brand, lengkap dengan copywriting agar pesan yang disampaikan lebih tepat sasaran ke audiens kamu.',
 ARRAY['12 desain feed per bulan', '8 desain story per bulan', 'Copywriting untuk setiap konten', 'Konsep konten mengikuti kalender bulanan', 'Revisi hingga 2x per konten', 'File siap unggah (format Instagram & TikTok)'],
 ARRAY['/images/portofolio9.jpg'],
 '/images/portofolio9.jpg', 4),
('aplikasi-reservasi-online', 'Aplikasi Reservasi Online', 'Web Development', 'Rp 9.000.000',
 'Sistem reservasi berbasis web untuk mempermudah pemesanan pelanggan secara real-time.',
 'Permudah proses pemesanan pelanggan dengan sistem reservasi online berbasis web. Cocok untuk restoran, klinik, salon, hingga penyedia jasa lainnya yang membutuhkan sistem booking real-time lengkap dengan notifikasi dan manajemen jadwal, sehingga mengurangi risiko bentrok jadwal dan mempercepat proses pemesanan.',
 ARRAY['Sistem booking real-time', 'Manajemen jadwal & slot ketersediaan', 'Notifikasi email/WhatsApp otomatis', 'Panel admin untuk kelola reservasi', 'Riwayat & laporan reservasi', 'Tampilan responsif di semua perangkat'],
 ARRAY['/images/portofolio3.jpg', '/images/portofolio9.jpg'],
 '/images/portofolio3.jpg', 5);

insert into services (slug, title, description, long_description, benefits, icon, sort_order) values
('web-development', 'Web Development',
 'Jasa pembuatan website company profile, landing page, hingga aplikasi web custom yang cepat, responsif, dan mudah dikelola.',
 'Kami membangun website yang cepat, responsif, dan mudah dikelola, mulai dari company profile, landing page, hingga aplikasi web custom. Setiap proyek dikerjakan dengan struktur kode yang rapi dan siap dikembangkan lebih lanjut.',
 ARRAY['Desain responsif di semua perangkat', 'Performa loading yang cepat', 'Struktur kode yang mudah dikembangkan', 'Optimasi SEO dasar'],
 '/images/svg/web-development.svg', 0),
('graphic-design', 'Graphic Design',
 'Perkuat identitas visual brand kamu melalui logo, materi promosi, dan panduan brand yang konsisten di berbagai media.',
 'Tim desain kami membantu memperkuat identitas visual brand kamu melalui logo, materi promosi, hingga panduan brand yang konsisten di berbagai media, baik cetak maupun digital.',
 ARRAY['Konsep desain custom sesuai brand', 'Revisi hingga desain final disetujui', 'File siap pakai (vector & raster)', 'Konsisten di berbagai media'],
 '/images/svg/graphic-design.svg', 1),
('mobile-applications', 'Mobile Applications',
 'Pengembangan aplikasi mobile Android dan iOS yang intuitif, mulai dari desain, pengembangan, hingga rilis ke app store.',
 'Kami mengembangkan aplikasi mobile untuk Android dan iOS yang intuitif dan sesuai kebutuhan bisnis kamu, mulai dari tahap desain, pengembangan, hingga rilis ke app store.',
 ARRAY['Kompatibel Android & iOS', 'Antarmuka yang mudah digunakan', 'Integrasi API & backend', 'Pendampingan hingga rilis'],
 '/images/svg/ui-ux-design.svg', 2),
('ui-ux-design', 'UI UX Design',
 'Riset pengguna, wireframe, hingga prototype interaktif untuk pengalaman pengguna yang intuitif dan tampilan yang menarik.',
 'Kami merancang pengalaman pengguna yang intuitif dan tampilan antarmuka yang menarik, dimulai dari riset pengguna, wireframe, hingga prototype interaktif yang siap diuji.',
 ARRAY['Riset & pemetaan kebutuhan pengguna', 'Wireframe & prototype interaktif', 'Desain antarmuka yang konsisten', 'Uji coba kegunaan (usability testing)'],
 '/images/svg/product.svg', 3),
('social-media', 'Social Media',
 'Jaga konsistensi kehadiran brand kamu di media sosial lewat perencanaan konten, desain feed & story, dan copywriting yang tepat sasaran.',
 'Kami membantu menjaga konsistensi kehadiran brand kamu di media sosial melalui perencanaan konten, desain feed & story, hingga copywriting yang sesuai dengan target audiens.',
 ARRAY['Perencanaan konten bulanan', 'Desain feed & story menarik', 'Copywriting yang sesuai target audiens', 'Laporan performa konten'],
 '/images/svg/social-networking.svg', 4),
('digital-marketing', 'Digital Marketing',
 'Jangkau audiens yang tepat melalui strategi iklan berbayar, optimasi SEO, dan optimasi funnel konversi yang terukur.',
 'Kami membantu bisnis kamu menjangkau audiens yang tepat melalui strategi pemasaran digital, mulai dari iklan berbayar, SEO, hingga optimasi funnel konversi.',
 ARRAY['Strategi iklan berbayar (Ads)', 'Optimasi SEO', 'Analisis & laporan performa', 'Optimasi funnel konversi'],
 '/images/svg/usability.svg', 5);

insert into stories (slug, title, label, label_color, description, content, image, author, author_image, date, sort_order) values
('why-product-thinking-is-the-next-big-thing-in-ux-design', 'Kenapa Product Thinking Penting dalam UX Design', 'Creative', 'yellow',
 'Product thinking membantu tim desain fokus pada masalah pengguna, bukan sekadar tampilan antarmuka semata.',
 ARRAY['Banyak bisnis yang belum punya desainer full-time, sehingga tampilan produk digital sering dibangun tanpa proses riset yang memadai. Product thinking membantu menjembatani hal ini dengan menempatkan masalah pengguna di pusat setiap keputusan desain, bukan langsung melompat ke tampilan visual.',
       'Alih-alih memulai dari layar, product thinking dimulai dari pertanyaan mendasar: untuk siapa produk ini dibuat, masalah apa yang ingin diselesaikan, dan bagaimana cara mengukur keberhasilannya. Pendekatan ini mengubah cara tim berkolaborasi, menjadikan desain sebagai tanggung jawab bersama, bukan hanya tugas satu orang.',
       'Tim yang menerapkan product thinking cenderung menghasilkan fitur yang lebih sederhana, fokus, dan mudah dikembangkan lebih lanjut, karena setiap keputusan desain bisa ditelusuri kembali ke kebutuhan pengguna yang jelas.'],
 '/images/stories1.jpg', 'Tim Eleven Digital Indonesia', '/images/testimonial-1.png', '2026-01-12', 0),
('7-practical-tips-for-cheating-at-design', '7 Tips Praktis Membuat Desain Rapi Tanpa Jadi Desainer', 'Technology', 'blue',
 'Tim tanpa desainer khusus tetap bisa menghasilkan antarmuka yang rapi dengan beberapa shortcut praktis berikut.',
 ARRAY['Tidak semua bisnis memiliki desainer full-time, namun kebutuhan menghadirkan tampilan yang rapi dan profesional tetap ada. Berikut beberapa cara praktis agar tim non-desainer tetap bisa menghasilkan antarmuka yang enak dilihat dan digunakan.',
       'Mulailah dari design system dan komponen yang sudah teruji, alih-alih membangun dari nol. Gunakan kembali skala spasi, warna, dan tipografi yang sudah terbukti serasi, lalu batasi pilihan agar tampilan tetap konsisten di seluruh halaman.',
       'Jangan ragu meniru pola layout dari produk yang sudah kamu kagumi. Desain yang baik seringkali lahir dari penggunaan kembali pola yang sudah terbukti berhasil, bukan dari menciptakan ulang setiap elemen dari nol.'],
 '/images/stories2.jpg', 'Tim Eleven Digital Indonesia', '/images/testimonial-2.png', '2026-02-03', 1),
('wells-fargo-artificial-intelligence-and-machine', 'Belajar dari Wells Fargo: AI dan Machine Learning di Layanan Finansial', 'Creative', 'yellow',
 'Institusi finansial besar seperti Wells Fargo memanfaatkan AI untuk pengalaman pelanggan yang lebih baik dan lebih aman.',
 ARRAY['Institusi finansial besar seperti Wells Fargo telah lama bereksperimen dengan AI dan machine learning untuk meningkatkan pengalaman pelanggan dalam skala besar, mulai dari deteksi fraud hingga layanan perbankan berbasis percakapan.',
       'Mulai dari deteksi fraud prediktif hingga asisten perbankan berbasis percakapan, sistem-sistem ini sangat bergantung pada antarmuka yang dirancang dengan baik agar otomasi yang kompleks tetap mudah dipahami dan dipercaya oleh pengguna sehari-hari.',
       'Pelajaran bagi tim yang lebih kecil pun sama: sehebat apapun teknologi di balik sebuah produk, keberhasilannya tetap bergantung pada seberapa jelas pengalaman tersebut dikomunikasikan kepada penggunanya.'],
 '/images/stories3.jpg', 'Tim Eleven Digital Indonesia', '/images/testimonial-3.png', '2026-03-18', 2),
('apple-maps-vs-google-maps-which-is-better', 'Apple Maps vs Google Maps: Mana yang Lebih Unggul?', 'Technology', 'blue',
 'Perbandingan Apple Maps dan Google Maps menunjukkan bagaimana keputusan desain kecil membentuk pengalaman yang sangat berbeda.',
 ARRAY['Membandingkan Apple Maps dan Google Maps adalah latihan yang baik untuk memahami bagaimana keputusan desain kecil dapat menghasilkan pengalaman yang sangat berbeda bagi penggunanya.',
       'Google Maps mengandalkan kepadatan data dan informasi real-time, sementara Apple Maps berfokus pada kejelasan visual dan interaksi yang lebih halus. Tidak ada pendekatan yang secara universal lebih baik, semua tergantung apa yang paling dibutuhkan pengguna pada momen tertentu.',
       'Pelajaran bagi tim produk: pahami prioritas pengguna Anda terlebih dahulu sebelum memutuskan untuk mengoptimalkan kekayaan informasi atau kesederhanaan visual.'],
 '/images/stories4.jpg', 'Tim Eleven Digital Indonesia', '/images/testimonial-4.png', '2026-04-22', 3);

insert into team_members (slug, name, position, bio, long_bio, email, socials, sort_order) values
('andika-pratama', 'Andika Pratama', 'Chief Executive Officer',
 'Memimpin visi dan strategi Eleven Digital Indonesia sejak awal berdiri.',
 'Andika memiliki pengalaman lebih dari 10 tahun di industri kreatif digital. Ia memimpin arah bisnis dan strategi pertumbuhan Eleven Digital Indonesia, memastikan setiap proyek yang dikerjakan tim selaras dengan visi perusahaan untuk membantu bisnis klien tampil lebih profesional di dunia digital.',
 'andika@elevendigital.com', '{"instagram": "#", "facebook": "#"}'::jsonb, 0),
('sarah-wijaya', 'Sarah Wijaya', 'Chief Operating Officer',
 'Mengelola operasional harian dan memastikan setiap proyek berjalan lancar.',
 'Sarah bertanggung jawab atas kelancaran operasional perusahaan, mulai dari manajemen tim, alur kerja proyek, hingga kualitas layanan yang diberikan ke klien. Dengan latar belakang manajemen proyek, ia memastikan setiap deadline terpenuhi tanpa mengorbankan kualitas.',
 'sarah@elevendigital.com', '{"instagram": "#", "facebook": "#"}'::jsonb, 1),
('raka-firmansyah', 'Raka Firmansyah', 'Chief Technology Officer',
 'Mengawal kualitas dan inovasi teknologi di setiap produk digital kami.',
 'Raka memimpin tim teknis dalam merancang arsitektur dan solusi teknologi untuk setiap proyek. Ia berfokus pada penerapan best practice pengembangan perangkat lunak agar produk yang dihasilkan aman, cepat, dan mudah dikembangkan di masa depan.',
 'raka@elevendigital.com', '{"instagram": "#", "twitter": "#"}'::jsonb, 2),
('dinda-permata', 'Dinda Permata', 'Creative Director',
 'Mengarahkan konsep visual dan kreativitas di setiap karya yang kami hasilkan.',
 'Dinda mengarahkan seluruh proses kreatif, mulai dari konsep desain, identitas visual brand, hingga eksekusi akhir setiap proyek. Ia percaya bahwa desain yang baik adalah perpaduan antara estetika dan fungsi yang menyelesaikan masalah nyata klien.',
 'dinda@elevendigital.com', '{"instagram": "#", "facebook": "#"}'::jsonb, 3),
('bima-santoso', 'Bima Santoso', 'Chief Marketing Officer',
 'Merancang strategi pemasaran agar brand klien menjangkau audiens yang tepat.',
 'Bima menangani strategi pemasaran digital, mulai dari perencanaan kampanye, optimasi iklan, hingga analisis performa. Fokus utamanya adalah memastikan setiap rupiah yang diinvestasikan klien memberikan hasil yang terukur.',
 'bima@elevendigital.com', '{"instagram": "#", "twitter": "#"}'::jsonb, 4),
('putri-anggraini', 'Putri Anggraini', 'Head of Finance & Admin',
 'Mengelola keuangan dan administrasi perusahaan secara transparan dan rapi.',
 'Putri bertanggung jawab atas pengelolaan keuangan, administrasi, dan legalitas perusahaan. Ia memastikan setiap proses transaksi dengan klien maupun vendor berjalan transparan, tercatat rapi, dan sesuai dengan standar akuntansi yang berlaku.',
 'putri@elevendigital.com', '{"instagram": "#", "facebook": "#"}'::jsonb, 5);

insert into projects (slug, title, category, year, image, href, description, long_description, services, sort_order) values
('freeport-indonesia', 'Freeport Indonesia', 'Web Development - Visual Interaktif', '2019', '/images/portofolio1.jpg', 'https://vip.kompas.com/perjalanan-kita-tembaga-dan-emas/',
 'Visual interaktif perjalanan tambang tembaga dan emas Freeport Indonesia.',
 'Sebuah halaman visual interaktif yang mengangkat perjalanan panjang PT Freeport Indonesia dalam industri pertambangan tembaga dan emas. Dikemas dengan storytelling yang imersif, animasi scroll, dan data visual agar pengunjung dapat memahami perjalanan perusahaan secara menarik.',
 ARRAY['Web Development', 'Visual Interaktif', 'Storytelling'], 0),
('kementerian-keuangan', 'Kementerian Keuangan', 'Web Development - Visual Interaktif', '2019', '/images/portofolio2.jpg', 'https://vip.kompas.com/umi/',
 'Kampanye visual interaktif Usaha Mikro Indonesia bersama Kementerian Keuangan.',
 'Proyek kolaborasi dengan Kementerian Keuangan untuk mengangkat kisah Usaha Mikro Indonesia (UMi) melalui halaman visual interaktif yang informatif, dilengkapi ilustrasi dan data statistik yang mudah dipahami masyarakat luas.',
 ARRAY['Web Development', 'Visual Interaktif', 'Data Visualization'], 1),
('kementerian-pupr', 'Kementerian PUPR', 'Web Development - Visual Interaktif', '2018', '/images/portofolio3.jpg', 'https://vip.kompas.com/serba-serbi-mudik/',
 'Halaman visual interaktif seputar mudik bersama Kementerian PUPR.',
 'Halaman visual interaktif yang menyajikan informasi seputar mudik, mulai dari jalur alternatif hingga tips perjalanan, dikemas secara menarik untuk mendukung kampanye Kementerian PUPR menjelang musim mudik.',
 ARRAY['Web Development', 'Visual Interaktif', 'Infografis'], 2),
('toyota-manufaktur-indonesia', 'Toyota Manufaktur Indonesia', 'Web Development - Visual Interaktif', '2018', '/images/portofolio4.jpg', 'https://vip.kompas.com/dari-indonesia-untuk-dunia/',
 'Kisah perjalanan manufaktur Toyota Indonesia untuk pasar dunia.',
 'Visual interaktif yang mengangkat kisah perjalanan Toyota Manufaktur Indonesia dalam memproduksi kendaraan berkualitas ekspor, menampilkan proses produksi dan pencapaian perusahaan dalam format yang mudah dinikmati.',
 ARRAY['Web Development', 'Visual Interaktif', 'Motion Graphic'], 3),
('frisian-flag', 'Frisian Flag', 'Web Development - Visual Interaktif', '2018', '/images/portofolio5.jpg', 'https://vip.kompas.com/keluarga-kuat-indonesia-hebat/',
 'Kampanye keluarga kuat Indonesia hebat bersama Frisian Flag.',
 'Halaman kampanye interaktif yang mengangkat semangat keluarga Indonesia, dirancang dengan visual hangat dan elemen interaktif agar pesan kampanye Frisian Flag lebih mudah tersampaikan ke audiens.',
 ARRAY['Web Development', 'Visual Interaktif', 'Campaign Landing Page'], 4),
('kawasaki-ninja', 'Kawasaki Ninja', 'Web Development - Visual Interaktif', '2019', '/images/portofolio6.jpg', 'https://vip.kompas.com/jejak-roda-sang-pionir/',
 'Jejak sejarah Kawasaki Ninja sebagai pionir motor sport di Indonesia.',
 'Halaman visual interaktif yang merunut jejak sejarah dan evolusi Kawasaki Ninja di Indonesia, lengkap dengan galeri produk dari masa ke masa dan elemen animasi yang dinamis.',
 ARRAY['Web Development', 'Visual Interaktif', 'Timeline Interaktif'], 5),
('meet-kcm', 'Meet KCM', 'Web Development - Landing Page', '2017', '/images/portofolio7.jpg', 'https://meetkcm.com',
 'Landing page acara Meet KCM dengan desain modern dan informatif.',
 'Landing page untuk acara Meet KCM yang dirancang modern dan informatif, menampilkan detail acara, pembicara, hingga informasi pendaftaran dalam satu halaman yang mudah dinavigasi.',
 ARRAY['Web Development', 'Landing Page', 'UI/UX Design'], 6),
('rs-jakarta-heart-center', 'RS Jakarta Heart Center', 'Web Development - Company Profile', '2017', '/images/portofolio8.jpg', 'https://jakartaheartcenter.com',
 'Website company profile untuk RS Jakarta Heart Center.',
 'Website company profile untuk RS Jakarta Heart Center yang menampilkan layanan, fasilitas, dan informasi dokter secara profesional, dirancang agar mudah diakses oleh pasien dan keluarga.',
 ARRAY['Web Development', 'Company Profile', 'UI/UX Design'], 7),
('anugerah-telkomsel', 'Anugerah Telkomsel', 'Web Development - Visual Interaktif', '2016', '/images/portofolio9.jpg', 'https://vip.kompas.com/telkomsel/',
 'Halaman visual interaktif ajang penghargaan Anugerah Telkomsel.',
 'Halaman visual interaktif untuk mengangkat cerita dan momen ajang penghargaan Anugerah Telkomsel, dikemas dengan galeri foto dan narasi yang menarik bagi pengunjung.',
 ARRAY['Web Development', 'Visual Interaktif', 'Event Landing Page'], 8);

insert into testimonial_clients (slug, name, logo, sort_order) values
('client-1', 'Client 1', '/images/client-1.png', 0),
('client-2', 'Client 2', '/images/client-2.png', 1),
('client-3', 'Client 3', '/images/client-3.png', 2),
('client-4', 'Client 4', '/images/client-4.png', 3),
('client-5', 'Client 5', '/images/client-5.png', 4),
('client-6', 'Client 6', '/images/client-6.png', 5);

insert into page_sections (page_key, section_key, content) values
('home', 'hero', '{
  "eyebrow": "Digital Creative Agency",
  "title_prefix": "Wujudkan ",
  "title_highlight": "transformasi digital",
  "title_suffix": " bisnis Anda.",
  "cta_label": "Mulai Sekarang",
  "cta_href": "#contact",
  "secondary_label": "Lihat portofolio kami",
  "secondary_href": "#case-study",
  "image": "/images/cover-illustration.png"
}'::jsonb),
('home', 'about', '{
  "eyebrow": "Creative",
  "title": "Kenapa Memilih Eleven Digital Indonesia",
  "cta_label": "Pelajari Lebih Lanjut",
  "cta_href": "#services",
  "image": "/images/svg/celebration.svg"
}'::jsonb),
('home', 'contact', '{
  "eyebrow": "Contact",
  "title": "Punya Proyek Digital?",
  "submit_label": "Send Message",
  "image": "/images/svg/contact-us.svg"
}'::jsonb),
('home', 'services_header', '{"eyebrow": "Service", "title": "Layanan Digital yang Kami Sediakan", "cta_label": "Lihat Semua Layanan"}'::jsonb),
('home', 'products_header', '{"eyebrow": "Product", "title": "Produk yang Kami Jual", "cta_label": "Lihat Semua Produk"}'::jsonb),
('home', 'team_header', '{"eyebrow": "Team", "title": "Kenali Board of Directors Kami", "cta_label": "Lihat Semua Tim"}'::jsonb),
('home', 'stories_header', '{"eyebrow": "Stories", "title": "Stories", "cta_label": "Lihat Semua Stories"}'::jsonb),
('home', 'casestudy_header', '{"eyebrow": "Case Study", "title": "Karya Terbaru Kami", "cta_label": "Lihat Semua Case Study"}'::jsonb),
('home', 'testimonials_header', '{"eyebrow": "Testimonials", "title": "Dipercaya Berbagai Klien"}'::jsonb);

insert into site_settings (key, value) values
('contact', '{
  "phone": "+62877234999550",
  "whatsapp": "62877234999550",
  "address": {
    "streetAddress": "Jl. Kebon Jeruk Indah Utama 4",
    "addressLocality": "Jakarta Barat",
    "addressRegion": "DKI Jakarta",
    "addressCountry": "ID"
  }
}'::jsonb),
('nav_links', '[
  {"label": "Home", "href": "/#home"},
  {"label": "Services", "href": "/#services", "matchPath": "/services"},
  {"label": "Case Study", "href": "/#case-study", "matchPath": "/case-study"},
  {"label": "Product", "href": "/#products", "matchPath": "/products"},
  {"label": "Team", "href": "/#team", "matchPath": "/team"},
  {"label": "Our Stories", "href": "/#stories", "matchPath": "/stories"}
]'::jsonb),
('footer_links', '[
  {"title": "Web Development", "links": ["Company Profile", "E-Commerce", "ERP System", "Reservation System"]},
  {"title": "Graphic Design", "links": ["Branding Design", "Wedding Invitation", "Name Card", "Poster - Banner Design"]},
  {"title": "Digital Marketing", "links": ["Social Media Strategic", "SEO Optimaliazation", "Advertising Banner", "Copywriter"]}
]'::jsonb);
